- name: Download apt key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository to sources.list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: grafana
    state: present

- name: Update apt cache and install Grafana
  ansible.builtin.apt:
    update_cache: true
    package:
      - grafana

- name: Ensure Grafana is started and enabled
  ansible.builtin.systemd:
    service: grafana-server
    state: started
    enabled: true
